name: Deploy to GitHub Pages
on:
  schedule:
    - cron: 17 5 * * *
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup repository (all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "Michal" && git config user.email "BlackDragon17@users.noreply.github.com"
          npm run deploy